# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'GitHubSpy' do
pod 'JLRoutes', '1.5.5'
pod 'AFNetworking', '3.1.0'
pod 'CocoaLumberjack/Swift', '2.2.0'
end

target 'GitHubSpyTests' do

end

target 'GitHubSpyUITests' do

end

