platform :ios, '8.0'
use_frameworks!

target 'GitHubSpy' do
pod 'York', '0.3.1'
#pod 'York', :git => 'https://github.com/inacioferrarini/York.git', :branch => 'dev'
#pod 'York', :path => '~/Developer/Workspaces/Xcode/PODS/York'
pod 'XCGLogger', '3.3'
pod 'EasyMapping', '0.16.1'
pod 'SDWebImage', '3.7.5'
pod 'AFNetworking', '3.1.0'
end

target 'GitHubSpyTests' do

end

target 'GitHubSpyUITests' do

end

