# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'GitHubSpy' do
pod 'York', :git => 'https://github.com/inacioferrarini/York', :branch => 'feature/version_0.3.0'
pod 'XCGLogger', '3.3'
pod 'EasyMapping', '0.16.1'
pod 'SDWebImage', '3.7.5'
pod 'AFNetworking', '3.1.0'
end

target 'GitHubSpyTests' do

end

target 'GitHubSpyUITests' do

end

